const fallbackStock={mermelada_fresa:true,mermelada_pina:true,mermelada_mora:true,mermelada_durazno:true,mermelada_ciruela:false,mermelada_granola:true,natural_1kilo:true,natural_1kilo_mermelada:true,natural_1kilo_ciruelas:false,natural_vaso8oz:true,parfait_8oz:true,parfait_14oz:true,parfait_bowl16oz:true,frasco_fresa:true,frasco_pina:true,frasco_mora:true,frasco_durazno:true,frasco_ciruelas:false};
const labels={mermelada_fresa:'Mermelada de fresa',mermelada_pina:'Mermelada de piña',mermelada_mora:'Mermelada de mora',mermelada_durazno:'Mermelada de durazno',mermelada_ciruela:'Mermelada de ciruela',mermelada_granola:'Mermelada con granola',natural_1kilo:'Yogurt natural · 1 kg',natural_1kilo_mermelada:'Natural · 1 kg con mermelada',natural_1kilo_ciruelas:'Natural · 1 kg con ciruelas',natural_vaso8oz:'Yogurt natural · 8 oz',parfait_8oz:'Parfait · 8 oz',parfait_14oz:'Parfait · 14 oz',parfait_bowl16oz:'Parfait bowl · 16 oz',frasco_fresa:'Frasco fresa',frasco_pina:'Frasco piña',frasco_mora:'Frasco mora',frasco_durazno:'Frasco durazno',frasco_ciruelas:'Frasco ciruelas'};
const defaultOrders=[['#FG-1084','María González','Delivery · 2:30 pm','$24.50','pending','Por preparar'],['#FG-1083','José Rojas','Retiro en tienda','$18.00','ready','Listo'],['#FG-1082','Ana Márquez','Delivery · 1:00 pm','$36.00','delivery','En ruta'],['#FG-1081','Café Alborada','Retiro en tienda','$52.00','ready','Entregado']];
let stock={...fallbackStock},orders=JSON.parse(localStorage.getItem('fitgurt-enterprise-orders')||'null')||defaultOrders,activeFilter='all';const el=id=>document.getElementById(id);
function persistOrders(){localStorage.setItem('fitgurt-enterprise-orders',JSON.stringify(orders))}
function showToast(message){const toast=el('toast');toast.textContent=message;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove('show'),2800)}
function advanceOrder(id){const order=orders.find(o=>o[0]===id);if(order[4]==='pending'){order[4]='ready';order[5]='Listo'}else{order[4]='delivery';order[5]='En ruta'}persistOrders();renderOrders();showToast(`${id} actualizado: ${order[5].toLowerCase()}.`)}
function renderOrders(){const query=el('orderSearch')?.value.toLowerCase().trim()||'';const visible=orders.filter(o=>(activeFilter==='all'||o[4]===activeFilter)&&(`${o[0]} ${o[1]}`).toLowerCase().includes(query));el('ordersTable').innerHTML=visible.map(o=>`<tr><td><strong class="order-id">${o[0]}</strong><small>Hoy</small></td><td><strong>${o[1]}</strong><small>Cliente frecuente</small></td><td>${o[2]}</td><td><strong>${o[3]}</strong></td><td><span class="status ${o[4]}">${o[5]}</span></td><td>${o[4]!=='delivery'?`<button class="advance-order" data-id="${o[0]}">${o[4]==='pending'?'Marcar listo':'Despachar'}</button>`:'<button class="row-action" aria-label="Pedido en ruta">•••</button>'}</td></tr>`).join('');el('emptyOrders').hidden=visible.length!==0;el('orderCount').textContent=orders.filter(o=>o[4]==='pending').length;el('pendingOrders').textContent=orders.filter(o=>o[4]==='pending').length;document.querySelectorAll('.advance-order').forEach(button=>button.onclick=()=>advanceOrder(button.dataset.id));renderCustomers()}
function customerRecords(){return Object.values(orders.reduce((records,order)=>{const name=order[1],amount=Number(order[3].replace('$',''));if(!records[name])records[name]={name,amount:0,count:0};records[name].amount+=amount;records[name].count++;return records},{})).sort((a,b)=>b.amount-a.amount)}
function initials(name){return name.split(' ').map(part=>part[0]).slice(0,2).join('').toUpperCase()}
function renderCustomers(){const customers=customerRecords();el('customerTotal').textContent=customers.length;el('returningCustomers').textContent=customers.filter(customer=>customer.count>1).length;el('customersList').innerHTML=customers.slice(0,4).map(customer=>`<div class="customer-row"><span class="customer-avatar">${initials(customer.name)}</span><div><strong>${customer.name}</strong><small>${customer.count} pedido${customer.count===1?'':'s'} registrado${customer.count===1?'':'s'}</small></div><div class="customer-value"><b>$${customer.amount.toFixed(2)}</b><span>${customer.count>1?'RECURRENTE':'NUEVO'}</span></div></div>`).join('');el('emptyCustomers').hidden=customers.length!==0}
function titleFromKey(key){return labels[key]||key.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function renderStock(){const entries=Object.entries(stock);el('stockList').innerHTML=entries.map(([key,on])=>`<label class="stock-item"><span class="product-dot ${key.includes('mora')?'mora':key.includes('granola')?'granola':'fresa'}"></span><div><strong>${titleFromKey(key)}</strong><small class="${on?'':'off'}">${on?'Disponible para vender':'Pausado temporalmente'}</small></div><input class="switch" data-key="${key}" type="checkbox" ${on?'checked':''}></label>`).join('');const active=entries.filter(([,on])=>on).length;el('stockAvailable').textContent=active;el('activeProducts').textContent=active;document.querySelectorAll('.switch').forEach(toggle=>toggle.onchange=()=>{stock[toggle.dataset.key]=toggle.checked;localStorage.setItem('fitgurt-enterprise-stock',JSON.stringify(stock));renderStock();el('stockNotice').textContent='● Cambios guardados localmente';showToast('Inventario actualizado.')})}
async function loadStock(){try{const local=localStorage.getItem('fitgurt-enterprise-stock');if(local){stock={...stock,...JSON.parse(local)};el('stockNotice').textContent='● Inventario local sincronizado'}else{const response=await fetch('./stock.json',{cache:'no-store'});if(response.ok){stock={...stock,...await response.json()};el('stockNotice').textContent='● Sincronizado con stock.json'}}}catch{el('stockNotice').textContent='● Modo local activo'}renderStock()}
function downloadCsv(filename,content){const url=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=filename;link.click();URL.revokeObjectURL(url)}
function exportStock(){downloadCsv('fitgurt-inventario.csv','producto,disponible\n'+Object.entries(stock).map(([key,on])=>`"${titleFromKey(key)}",${on?'si':'no'}`).join('\n'))}
function exportCustomers(){downloadCsv('fitgurt-clientes.csv','cliente,pedidos,total_usd\n'+customerRecords().map(customer=>`"${customer.name}",${customer.count},${customer.amount.toFixed(2)}`).join('\n'));showToast('Exportación de clientes lista.')}
el('newOrder').onclick=()=>el('orderDialog').showModal();el('saveOrder').onclick=event=>{const name=el('customerName'),total=el('orderTotal');if(!name.checkValidity()||!total.checkValidity()){event.preventDefault();return}orders.unshift([`#FG-${1085+orders.length}`,name.value,el('deliveryType').value,'$'+Number(total.value).toFixed(2),'pending','Por preparar']);persistOrders();el('todayOrders').textContent=Number(el('todayOrders').textContent)+1;el('todaySales').textContent=(Number(el('todaySales').textContent)+Number(total.value)).toFixed(2);renderOrders();showToast('Pedido registrado y agregado a preparación.');name.value=total.value=''};el('exportStock').onclick=exportStock;el('exportCustomers').onclick=exportCustomers;el('orderSearch').oninput=renderOrders;document.querySelectorAll('.filter').forEach(button=>button.onclick=()=>{activeFilter=button.dataset.filter;document.querySelectorAll('.filter').forEach(item=>item.classList.toggle('active',item===button));renderOrders()});el('showAllOrders').onclick=()=>{activeFilter='all';document.querySelectorAll('.filter').forEach(item=>item.classList.toggle('active',item.dataset.filter==='all'));el('orderSearch').value='';renderOrders();el('pedidos').scrollIntoView({behavior:'smooth'})};document.querySelector('.menu-toggle').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');renderOrders();loadStock();
